#!/bin/bash
#
# Copyright 2018-2025 Facundo Batista

set -eu

if [ $# -ne 0 ]; then
    TARGET_TESTS="$@"
else
    TARGET_TESTS="infoauth tests"
fi

fades -r requirements-tests.txt -x python -m pytest -sv $TARGET_TESTS
